### ISSUE TITLE
Clarify licensing

### ISSUE THREAD

**Issue by obazoud** [jasimmons/chef-serverspec#1]
Choose a licence: MIT, Apache, ...

I see "All rights reserved - Do Not Redistribute"
- https://github.com/jasimmons/chef-serverspec/blob/master/metadata.rb#L4
- https://github.com/jasimmons/chef-serverspec/blob/master/recipes/default.rb#L7

**Comment by obazoud** [comment]
any news ?
I got some pull requests to send but without clarify licensing...

**Comment by jasimmons** [comment]
I apologize for the delay @obazoud. I'll update the licensing as Apache.

**Comment by jasimmons** [comment]
LICENSE updated with 0.2.0 release.
